// PAL-only localized UI images (generated by tools/pal/gen_ui_langs.py)
#pragma once
#include "alignment.h"
static const ALIGN_ASSET(2) char de_ui_files_option_mono_off_pal[] = "__OTR__ui_langs/de/ui/files/option_mono_off.pal";
static const ALIGN_ASSET(2) char de_ui_files_option_mono_off_png[] = "__OTR__ui_langs/de/ui/files/option_mono_off";
static const ALIGN_ASSET(2) char de_ui_files_option_mono_on_pal[] = "__OTR__ui_langs/de/ui/files/option_mono_on.pal";
static const ALIGN_ASSET(2) char de_ui_files_option_mono_on_png[] = "__OTR__ui_langs/de/ui/files/option_mono_on";
static const ALIGN_ASSET(2) char de_ui_files_option_stereo_off_pal[] = "__OTR__ui_langs/de/ui/files/option_stereo_off.pal";
static const ALIGN_ASSET(2) char de_ui_files_option_stereo_off_png[] = "__OTR__ui_langs/de/ui/files/option_stereo_off";
static const ALIGN_ASSET(2) char de_ui_files_option_stereo_on_pal[] = "__OTR__ui_langs/de/ui/files/option_stereo_on.pal";
static const ALIGN_ASSET(2) char de_ui_files_option_stereo_on_png[] = "__OTR__ui_langs/de/ui/files/option_stereo_on";
static const ALIGN_ASSET(2) char de_ui_pause_bp_needed_pal[] = "__OTR__ui_langs/de/ui/pause/bp_needed.pal";
static const ALIGN_ASSET(2) char de_ui_pause_bp_needed_png[] = "__OTR__ui_langs/de/ui/pause/bp_needed";
static const ALIGN_ASSET(2) char de_ui_pause_label_badges_pal[] = "__OTR__ui_langs/de/ui/pause/label_badges.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_badges_png[] = "__OTR__ui_langs/de/ui/pause/label_badges";
static const ALIGN_ASSET(2) char de_ui_pause_label_items_pal[] = "__OTR__ui_langs/de/ui/pause/label_items.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_items_png[] = "__OTR__ui_langs/de/ui/pause/label_items";
static const ALIGN_ASSET(2) char de_ui_pause_label_map_pal[] = "__OTR__ui_langs/de/ui/pause/label_map.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_map_png[] = "__OTR__ui_langs/de/ui/pause/label_map";
static const ALIGN_ASSET(2) char de_ui_pause_label_party_pal[] = "__OTR__ui_langs/de/ui/pause/label_party.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_party_png[] = "__OTR__ui_langs/de/ui/pause/label_party";
static const ALIGN_ASSET(2) char de_ui_pause_label_spirits_pal[] = "__OTR__ui_langs/de/ui/pause/label_spirits.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_spirits_png[] = "__OTR__ui_langs/de/ui/pause/label_spirits";
static const ALIGN_ASSET(2) char de_ui_pause_label_stats_pal[] = "__OTR__ui_langs/de/ui/pause/label_stats.pal";
static const ALIGN_ASSET(2) char de_ui_pause_label_stats_png[] = "__OTR__ui_langs/de/ui/pause/label_stats";
static const ALIGN_ASSET(2) char es_ui_files_option_mono_off_pal[] = "__OTR__ui_langs/es/ui/files/option_mono_off.pal";
static const ALIGN_ASSET(2) char es_ui_files_option_mono_off_png[] = "__OTR__ui_langs/es/ui/files/option_mono_off";
static const ALIGN_ASSET(2) char es_ui_files_option_mono_on_pal[] = "__OTR__ui_langs/es/ui/files/option_mono_on.pal";
static const ALIGN_ASSET(2) char es_ui_files_option_mono_on_png[] = "__OTR__ui_langs/es/ui/files/option_mono_on";
static const ALIGN_ASSET(2) char es_ui_files_option_stereo_off_pal[] = "__OTR__ui_langs/es/ui/files/option_stereo_off.pal";
static const ALIGN_ASSET(2) char es_ui_files_option_stereo_off_png[] = "__OTR__ui_langs/es/ui/files/option_stereo_off";
static const ALIGN_ASSET(2) char es_ui_files_option_stereo_on_pal[] = "__OTR__ui_langs/es/ui/files/option_stereo_on.pal";
static const ALIGN_ASSET(2) char es_ui_files_option_stereo_on_png[] = "__OTR__ui_langs/es/ui/files/option_stereo_on";
static const ALIGN_ASSET(2) char es_ui_pause_bp_needed_pal[] = "__OTR__ui_langs/es/ui/pause/bp_needed.pal";
static const ALIGN_ASSET(2) char es_ui_pause_bp_needed_png[] = "__OTR__ui_langs/es/ui/pause/bp_needed";
static const ALIGN_ASSET(2) char es_ui_pause_label_badges_pal[] = "__OTR__ui_langs/es/ui/pause/label_badges.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_badges_png[] = "__OTR__ui_langs/es/ui/pause/label_badges";
static const ALIGN_ASSET(2) char es_ui_pause_label_items_pal[] = "__OTR__ui_langs/es/ui/pause/label_items.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_items_png[] = "__OTR__ui_langs/es/ui/pause/label_items";
static const ALIGN_ASSET(2) char es_ui_pause_label_map_pal[] = "__OTR__ui_langs/es/ui/pause/label_map.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_map_png[] = "__OTR__ui_langs/es/ui/pause/label_map";
static const ALIGN_ASSET(2) char es_ui_pause_label_party_pal[] = "__OTR__ui_langs/es/ui/pause/label_party.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_party_png[] = "__OTR__ui_langs/es/ui/pause/label_party";
static const ALIGN_ASSET(2) char es_ui_pause_label_spirits_pal[] = "__OTR__ui_langs/es/ui/pause/label_spirits.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_spirits_png[] = "__OTR__ui_langs/es/ui/pause/label_spirits";
static const ALIGN_ASSET(2) char es_ui_pause_label_stats_pal[] = "__OTR__ui_langs/es/ui/pause/label_stats.pal";
static const ALIGN_ASSET(2) char es_ui_pause_label_stats_png[] = "__OTR__ui_langs/es/ui/pause/label_stats";
static const ALIGN_ASSET(2) char fr_ui_files_option_mono_off_pal[] = "__OTR__ui_langs/fr/ui/files/option_mono_off.pal";
static const ALIGN_ASSET(2) char fr_ui_files_option_mono_off_png[] = "__OTR__ui_langs/fr/ui/files/option_mono_off";
static const ALIGN_ASSET(2) char fr_ui_files_option_mono_on_pal[] = "__OTR__ui_langs/fr/ui/files/option_mono_on.pal";
static const ALIGN_ASSET(2) char fr_ui_files_option_mono_on_png[] = "__OTR__ui_langs/fr/ui/files/option_mono_on";
static const ALIGN_ASSET(2) char fr_ui_files_option_stereo_off_pal[] = "__OTR__ui_langs/fr/ui/files/option_stereo_off.pal";
static const ALIGN_ASSET(2) char fr_ui_files_option_stereo_off_png[] = "__OTR__ui_langs/fr/ui/files/option_stereo_off";
static const ALIGN_ASSET(2) char fr_ui_files_option_stereo_on_pal[] = "__OTR__ui_langs/fr/ui/files/option_stereo_on.pal";
static const ALIGN_ASSET(2) char fr_ui_files_option_stereo_on_png[] = "__OTR__ui_langs/fr/ui/files/option_stereo_on";
static const ALIGN_ASSET(2) char fr_ui_pause_bp_needed_pal[] = "__OTR__ui_langs/fr/ui/pause/bp_needed.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_bp_needed_png[] = "__OTR__ui_langs/fr/ui/pause/bp_needed";
static const ALIGN_ASSET(2) char fr_ui_pause_label_badges_pal[] = "__OTR__ui_langs/fr/ui/pause/label_badges.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_badges_png[] = "__OTR__ui_langs/fr/ui/pause/label_badges";
static const ALIGN_ASSET(2) char fr_ui_pause_label_items_pal[] = "__OTR__ui_langs/fr/ui/pause/label_items.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_items_png[] = "__OTR__ui_langs/fr/ui/pause/label_items";
static const ALIGN_ASSET(2) char fr_ui_pause_label_map_pal[] = "__OTR__ui_langs/fr/ui/pause/label_map.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_map_png[] = "__OTR__ui_langs/fr/ui/pause/label_map";
static const ALIGN_ASSET(2) char fr_ui_pause_label_party_pal[] = "__OTR__ui_langs/fr/ui/pause/label_party.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_party_png[] = "__OTR__ui_langs/fr/ui/pause/label_party";
static const ALIGN_ASSET(2) char fr_ui_pause_label_spirits_pal[] = "__OTR__ui_langs/fr/ui/pause/label_spirits.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_spirits_png[] = "__OTR__ui_langs/fr/ui/pause/label_spirits";
static const ALIGN_ASSET(2) char fr_ui_pause_label_stats_pal[] = "__OTR__ui_langs/fr/ui/pause/label_stats.pal";
static const ALIGN_ASSET(2) char fr_ui_pause_label_stats_png[] = "__OTR__ui_langs/fr/ui/pause/label_stats";
static const ALIGN_ASSET(2) char ui_battle_status_danger_de_pal[] = "__OTR__ui_langs/de/ui/battle/status/danger.pal";
static const ALIGN_ASSET(2) char ui_battle_status_danger_de_png[] = "__OTR__ui_langs/de/ui/battle/status/danger";
static const ALIGN_ASSET(2) char ui_battle_status_danger_es_pal[] = "__OTR__ui_langs/es/ui/battle/status/danger.pal";
static const ALIGN_ASSET(2) char ui_battle_status_danger_es_png[] = "__OTR__ui_langs/es/ui/battle/status/danger";
static const ALIGN_ASSET(2) char ui_battle_status_danger_fr_pal[] = "__OTR__ui_langs/fr/ui/battle/status/danger.pal";
static const ALIGN_ASSET(2) char ui_battle_status_danger_fr_png[] = "__OTR__ui_langs/fr/ui/battle/status/danger";
static const ALIGN_ASSET(2) char ui_battle_status_happy_de_pal[] = "__OTR__ui_langs/de/ui/battle/status/happy.pal";
static const ALIGN_ASSET(2) char ui_battle_status_happy_de_png[] = "__OTR__ui_langs/de/ui/battle/status/happy";
static const ALIGN_ASSET(2) char ui_battle_status_happy_es_pal[] = "__OTR__ui_langs/es/ui/battle/status/happy.pal";
static const ALIGN_ASSET(2) char ui_battle_status_happy_es_png[] = "__OTR__ui_langs/es/ui/battle/status/happy";
static const ALIGN_ASSET(2) char ui_battle_status_happy_fr_pal[] = "__OTR__ui_langs/fr/ui/battle/status/happy.pal";
static const ALIGN_ASSET(2) char ui_battle_status_happy_fr_png[] = "__OTR__ui_langs/fr/ui/battle/status/happy";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_de_pal[] = "__OTR__ui_langs/de/ui/battle/status/hp_drain.pal";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_de_png[] = "__OTR__ui_langs/de/ui/battle/status/hp_drain";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_es_pal[] = "__OTR__ui_langs/es/ui/battle/status/hp_drain.pal";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_es_png[] = "__OTR__ui_langs/es/ui/battle/status/hp_drain";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_fr_pal[] = "__OTR__ui_langs/fr/ui/battle/status/hp_drain.pal";
static const ALIGN_ASSET(2) char ui_battle_status_hp_drain_fr_png[] = "__OTR__ui_langs/fr/ui/battle/status/hp_drain";
static const ALIGN_ASSET(2) char ui_battle_status_peril_de_pal[] = "__OTR__ui_langs/de/ui/battle/status/peril.pal";
static const ALIGN_ASSET(2) char ui_battle_status_peril_de_png[] = "__OTR__ui_langs/de/ui/battle/status/peril";
static const ALIGN_ASSET(2) char ui_battle_status_peril_es_pal[] = "__OTR__ui_langs/es/ui/battle/status/peril.pal";
static const ALIGN_ASSET(2) char ui_battle_status_peril_es_png[] = "__OTR__ui_langs/es/ui/battle/status/peril";
static const ALIGN_ASSET(2) char ui_battle_status_peril_fr_pal[] = "__OTR__ui_langs/fr/ui/battle/status/peril.pal";
static const ALIGN_ASSET(2) char ui_battle_status_peril_fr_png[] = "__OTR__ui_langs/fr/ui/battle/status/peril";
static const ALIGN_ASSET(2) char ui_battle_status_refund_de_pal[] = "__OTR__ui_langs/de/ui/battle/status/refund.pal";
static const ALIGN_ASSET(2) char ui_battle_status_refund_de_png[] = "__OTR__ui_langs/de/ui/battle/status/refund";
static const ALIGN_ASSET(2) char ui_battle_status_refund_es_pal[] = "__OTR__ui_langs/es/ui/battle/status/refund.pal";
static const ALIGN_ASSET(2) char ui_battle_status_refund_es_png[] = "__OTR__ui_langs/es/ui/battle/status/refund";
static const ALIGN_ASSET(2) char ui_battle_status_refund_fr_pal[] = "__OTR__ui_langs/fr/ui/battle/status/refund.pal";
static const ALIGN_ASSET(2) char ui_battle_status_refund_fr_png[] = "__OTR__ui_langs/fr/ui/battle/status/refund";
static const ALIGN_ASSET(2) char ui_fp_cost_de_notenough_pal[] = "__OTR__ui_langs/de/ui/fp_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_de_pal[] = "__OTR__ui_langs/de/ui/fp_cost.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_de_png[] = "__OTR__ui_langs/de/ui/fp_cost";
static const ALIGN_ASSET(2) char ui_fp_cost_de_reduced_pal[] = "__OTR__ui_langs/de/ui/fp_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_de_reduced_twice_pal[] = "__OTR__ui_langs/de/ui/fp_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_es_notenough_pal[] = "__OTR__ui_langs/es/ui/fp_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_es_pal[] = "__OTR__ui_langs/es/ui/fp_cost.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_es_png[] = "__OTR__ui_langs/es/ui/fp_cost";
static const ALIGN_ASSET(2) char ui_fp_cost_es_reduced_pal[] = "__OTR__ui_langs/es/ui/fp_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_es_reduced_twice_pal[] = "__OTR__ui_langs/es/ui/fp_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_fr_notenough_pal[] = "__OTR__ui_langs/fr/ui/fp_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_fr_pal[] = "__OTR__ui_langs/fr/ui/fp_cost.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_fr_png[] = "__OTR__ui_langs/fr/ui/fp_cost";
static const ALIGN_ASSET(2) char ui_fp_cost_fr_reduced_pal[] = "__OTR__ui_langs/fr/ui/fp_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_fp_cost_fr_reduced_twice_pal[] = "__OTR__ui_langs/fr/ui/fp_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_de_notenough_pal[] = "__OTR__ui_langs/de/ui/pow_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_de_pal[] = "__OTR__ui_langs/de/ui/pow_cost.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_de_png[] = "__OTR__ui_langs/de/ui/pow_cost";
static const ALIGN_ASSET(2) char ui_pow_cost_de_reduced_pal[] = "__OTR__ui_langs/de/ui/pow_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_de_reduced_twice_pal[] = "__OTR__ui_langs/de/ui/pow_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_es_notenough_pal[] = "__OTR__ui_langs/es/ui/pow_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_es_pal[] = "__OTR__ui_langs/es/ui/pow_cost.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_es_png[] = "__OTR__ui_langs/es/ui/pow_cost";
static const ALIGN_ASSET(2) char ui_pow_cost_es_reduced_pal[] = "__OTR__ui_langs/es/ui/pow_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_es_reduced_twice_pal[] = "__OTR__ui_langs/es/ui/pow_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_fr_notenough_pal[] = "__OTR__ui_langs/fr/ui/pow_cost.notenough.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_fr_pal[] = "__OTR__ui_langs/fr/ui/pow_cost.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_fr_png[] = "__OTR__ui_langs/fr/ui/pow_cost";
static const ALIGN_ASSET(2) char ui_pow_cost_fr_reduced_pal[] = "__OTR__ui_langs/fr/ui/pow_cost.reduced.pal";
static const ALIGN_ASSET(2) char ui_pow_cost_fr_reduced_twice_pal[] = "__OTR__ui_langs/fr/ui/pow_cost.reduced_twice.pal";
static const ALIGN_ASSET(2) char ui_status_text_fp_de_pal[] = "__OTR__ui_langs/de/ui/status/text_fp.pal";
static const ALIGN_ASSET(2) char ui_status_text_fp_de_png[] = "__OTR__ui_langs/de/ui/status/text_fp";
static const ALIGN_ASSET(2) char ui_status_text_fp_es_pal[] = "__OTR__ui_langs/es/ui/status/text_fp.pal";
static const ALIGN_ASSET(2) char ui_status_text_fp_es_png[] = "__OTR__ui_langs/es/ui/status/text_fp";
static const ALIGN_ASSET(2) char ui_status_text_fp_fr_pal[] = "__OTR__ui_langs/fr/ui/status/text_fp.pal";
static const ALIGN_ASSET(2) char ui_status_text_fp_fr_png[] = "__OTR__ui_langs/fr/ui/status/text_fp";
static const ALIGN_ASSET(2) char ui_status_text_hp_de_pal[] = "__OTR__ui_langs/de/ui/status/text_hp.pal";
static const ALIGN_ASSET(2) char ui_status_text_hp_de_png[] = "__OTR__ui_langs/de/ui/status/text_hp";
static const ALIGN_ASSET(2) char ui_status_text_hp_es_pal[] = "__OTR__ui_langs/es/ui/status/text_hp.pal";
static const ALIGN_ASSET(2) char ui_status_text_hp_es_png[] = "__OTR__ui_langs/es/ui/status/text_hp";
static const ALIGN_ASSET(2) char ui_status_text_hp_fr_pal[] = "__OTR__ui_langs/fr/ui/status/text_hp.pal";
static const ALIGN_ASSET(2) char ui_status_text_hp_fr_png[] = "__OTR__ui_langs/fr/ui/status/text_hp";
#define ui_fp_cost_de_notenough_png ui_fp_cost_de_png
#define ui_fp_cost_de_reduced_png ui_fp_cost_de_png
#define ui_fp_cost_de_reduced_twice_png ui_fp_cost_de_png
#define ui_fp_cost_es_notenough_png ui_fp_cost_es_png
#define ui_fp_cost_es_reduced_png ui_fp_cost_es_png
#define ui_fp_cost_es_reduced_twice_png ui_fp_cost_es_png
#define ui_fp_cost_fr_notenough_png ui_fp_cost_fr_png
#define ui_fp_cost_fr_reduced_png ui_fp_cost_fr_png
#define ui_fp_cost_fr_reduced_twice_png ui_fp_cost_fr_png
#define ui_pow_cost_de_notenough_png ui_pow_cost_de_png
#define ui_pow_cost_de_reduced_png ui_pow_cost_de_png
#define ui_pow_cost_de_reduced_twice_png ui_pow_cost_de_png
#define ui_pow_cost_es_notenough_png ui_pow_cost_es_png
#define ui_pow_cost_es_reduced_png ui_pow_cost_es_png
#define ui_pow_cost_es_reduced_twice_png ui_pow_cost_es_png
#define ui_pow_cost_fr_notenough_png ui_pow_cost_fr_png
#define ui_pow_cost_fr_reduced_png ui_pow_cost_fr_png
#define ui_pow_cost_fr_reduced_twice_png ui_pow_cost_fr_png
