import sys,re,subprocess,glob
sys.path.insert(0,'/home/claude/work')
from layout import simulate
res,iss=simulate('pal')
LANGS=('de','fr','es')
def norm(n): return re.sub(r'[/.]','_',n)
# collect wanted identifiers from compile errors
wanted=set()
for f in glob.glob('/home/claude/work/all_PAL/*.txt'):
    for m in re.finditer(r"undeclared identifier '([^']*_(?:png|pal))'",open(f).read()): wanted.add(m.group(1))
ent={}
for e in res:
    n=e['name']
    if not n or e['sim'] is None: continue
    for l in LANGS:
        if n.startswith(l+'/'):
            ent[(l,norm(n[len(l)+1:]),e['type'])]=e
def key(ident):
    m=re.match(r'^(.*)_(png|pal)$',ident); base,kind=m.groups()
    for l in LANGS:
        if base.startswith(l+'_'): return l,base[len(l)+1:],kind
        if re.search(r'_'+l+r'(_|$)',base):
            return l,re.sub(r'_'+l+r'(?=_|$)','',base,count=1),kind
    return None
FMT={'ci4':'CI4','ci8':'CI8','ia4':'IA4','ia8':'IA8','ia16':'IA16','i4':'I4','i8':'I8','rgba16':'RGBA16','rgba32':'RGBA32'}
yml={};hdr=[];alias=[];miss=[]
used={}
for ident in sorted(wanted):
    k=key(ident)
    if not k: miss.append(ident); continue
    l,b,kind=k
    if kind=='png':
        e=ent.get((l,b,res and 'ci4')) 
        e=None
        for t in FMT:
            if (l,b,t) in ent: e=ent[(l,b,t)]; break
        if e is None:
            # alias to base png (reduced/notenough variants share the image)
            bb=re.sub(r'_(reduced_twice|reduced|notenough)$','',b)
            if bb!=b:
                for t in FMT:
                    if (l,bb,t) in ent: alias.append((ident,l,bb)); break
                else: miss.append(ident)
            else: miss.append(ident)
            continue
        a=e['args']; path=f"ui_langs/{l}/{e['name'][len(l)+1:]}"
        yml[e['name']]=f"  {{ type: TEXTURE, format: {FMT[e['type']]}, offset: 0x{e['sim']:X}, width: {a[0]}, height: {a[1]}, symbol: {ident} }}"
        hdr.append((ident,f"__OTR__ui_langs/{e['name']}"))
    else:
        e=ent.get((l,b,'palette'))
        if e is None: miss.append(ident); continue
        # palette color count from preceding image type
        yml[e['name']+'.pal']=f"  {{ type: TEXTURE, format: TLUT, offset: 0x{e['sim']:X}, colors: 16, symbol: {ident} }}"
        hdr.append((ident,f"__OTR__ui_langs/{e['name']}.pal"))
open('/home/claude/work/overrides/ui_langs.yml','w').write(''.join(f"{k}:\n{v}\n" for k,v in sorted(yml.items())))
h="// PAL-only localized UI images (generated by tools/pal/gen_ui_langs.py)\n#pragma once\n#include \"alignment.h\"\n"
for i,p in hdr: h+=f'static const ALIGN_ASSET(2) char {i}[] = "{p}";\n'
for i,l,bb in alias:
    base=re.sub(r'^(.*)$',lambda m:m.group(1),i)
    # find base symbol name by rebuilding ident without the variant
    tgt=[x for x,_ in hdr if x==re.sub(r'_(reduced_twice|reduced|notenough)_png$','_png',i)]
    if tgt: h+=f"#define {i} {tgt[0]}\n"
    else: miss.append(i)
open('/home/claude/PaperBoat/include/assets/ui_langs_pal.h','w').write(h)
print(len(wanted),'wanted',len(yml),'yaml',len(hdr),'hdr',len(alias),'alias','missing',miss)
