#include "common.h"
#include "entity.h"
#include "assets/misc/starpoint.h"

#if VERSION_PAL
#include "assets/starpoint_pal.h"
EntityModelScript EMS_starpoint_starpoint = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_en_render_starpoint_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoints = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_en_render_starpoints_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoint_de = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_de_render_starpoint_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoints_de = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_de_render_starpoints_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoint_fr = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_fr_render_starpoint_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoints_fr = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_fr_render_starpoints_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoint_es = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_es_render_starpoint_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoints_es = STANDARD_ENTITY_MODEL_SCRIPT(starpoint_es_render_starpoints_top_gfx, RENDER_MODE_CLOUD_NO_ZCMP);
#else
EntityModelScript EMS_starpoint_starpoint = STANDARD_ENTITY_MODEL_SCRIPT(D_802A2158_7A9AF8, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_starpoints = STANDARD_ENTITY_MODEL_SCRIPT(D_802A32D8_7AAC78, RENDER_MODE_CLOUD_NO_ZCMP);
#endif

EntityModelScript EMS_starpoint_digit_0 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A4410_7ABDB0, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_1 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A5530_7ACED0, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_2 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A6650_7ADFF0, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_3 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A7770_7AF110, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_4 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A8890_7B0230, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_5 = STANDARD_ENTITY_MODEL_SCRIPT(D_802A99B0_7B1350, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_6 = STANDARD_ENTITY_MODEL_SCRIPT(D_802AAAD0_7B2470, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_7 = STANDARD_ENTITY_MODEL_SCRIPT(D_802ABBF0_7B3590, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_8 = STANDARD_ENTITY_MODEL_SCRIPT(D_802ACD10_7B46B0, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_digit_9 = STANDARD_ENTITY_MODEL_SCRIPT(D_802ADE30_7B57D0, RENDER_MODE_CLOUD_NO_ZCMP);
EntityModelScript EMS_starpoint_dummy = STANDARD_ENTITY_MODEL_SCRIPT(D_802ADF90_7B5930, RENDER_MODE_CLOUD_NO_ZCMP);
